In [1]:
import numpy as np
import pandas as pd

In [2]:
incomes = [0, 0, 3, 120, 403, 1009, 20199, 19200, 50125, 90263]
expenses = [20000, 20000, 40000, 40000, 50000, 90000, 100000, 120000, 120000, 150000]
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct']

# Converting data to NumPy arrays
Could also have used `np.around(np_incomes_taxed, 2)` to make `np_incomes_taxed` human-readable right away

In [3]:
np_incomes = np.array(incomes)
np_incomes_taxed = np_incomes * 0.7
np_expenses = np.array(expenses)
np_incomes, np_incomes_taxed, np_expenses

(array([    0,     0,     3,   120,   403,  1009, 20199, 19200, 50125,
        90263]),
 array([0.00000e+00, 0.00000e+00, 2.10000e+00, 8.40000e+01, 2.82100e+02,
        7.06300e+02, 1.41393e+04, 1.34400e+04, 3.50875e+04, 6.31841e+04]),
 array([ 20000,  20000,  40000,  40000,  50000,  90000, 100000, 120000,
        120000, 150000]))

# Creating a DataFrame
- Prepare data in advance using a dictionary
- Now I can use months as indices for a clearer output

In [4]:
df_data_dict = {
    'Taxed Incomes' : np_incomes_taxed,
    'Expenses' : np_expenses
}
df_income_expenses = pd.DataFrame(df_data_dict, months)
df_income_expenses

Taxed Incomes  Expenses
Jan            0.0     20000
Feb            0.0     20000
Mar            2.1     40000
Apr           84.0     40000
May          282.1     50000
Jun          706.3     90000
Jul        14139.3    100000
Aug        13440.0    120000
Sep        35087.5    120000
Oct        63184.1    150000

## First quarter

In [5]:
first_quarter = df_income_expenses.loc['Jan':'Mar']
first_quarter

Taxed Incomes  Expenses
Jan            0.0     20000
Feb            0.0     20000
Mar            2.1     40000

# Conclusions:
- I think it could be useful to leave the indices as they are and just create a new column called `Months:`
- I would be interested in how they look as a graph for a visual understanding
- NumPy automatically converts ints to floats with multiplication if needed not to lose information, just like in regular Python